from io import BytesIO

import numpy as np
from reportlab.lib import colors
from reportlab.pdfgen import canvas


def generate_pdf(
    sample,
    Lab,
    XYZ,
    xy,
    rgb,
    gloss
):
    """
    Generate a PDF report for a single reflectance measurement.

    Parameters
    ----------
    sample : str
        Sample identifier.

    Lab : array-like
        [L*, a*, b*]

    XYZ : array-like
        [X, Y, Z]

    xy : array-like
        [x, y]

    rgb : tuple
        (R, G, B) values in range 0-255

    gloss : float
        Gloss value.

    Returns
    -------
    BytesIO
        PDF buffer ready for Streamlit download.
    """

    L, a, b = Lab[0], Lab[1], Lab[2]
    C = float(np.sqrt(a ** 2 + b ** 2))
    h = float(np.degrees(np.arctan2(b, a)) % 360)

    buffer = BytesIO()

    pdf = canvas.Canvas(buffer)

    # --------------------------------------------------
    # Title
    # --------------------------------------------------

    pdf.setFont("Helvetica-Bold", 18)

    pdf.drawString(
        50,
        800,
        "Colour Characterisation Report"
    )

    # --------------------------------------------------
    # Sample information
    # --------------------------------------------------

    pdf.setFont("Helvetica", 12)

    y = 760

    pdf.drawString(
        50,
        y,
        f"Sample: {sample}"
    )

    y -= 30

    # --------------------------------------------------
    # CIELAB
    # --------------------------------------------------

    pdf.setFont("Helvetica-Bold", 14)

    pdf.drawString(
        50,
        y,
        "CIELAB Coordinates"
    )

    pdf.setFont("Helvetica", 12)

    y -= 25

    pdf.drawString(
        70,
        y,
        f"L*: {Lab[0]:.2f}"
    )

    y -= 20

    pdf.drawString(
        70,
        y,
        f"a*: {Lab[1]:.2f}"
    )

    y -= 20

    pdf.drawString(
        70,
        y,
        f"b*: {Lab[2]:.2f}"
    )

    y -= 40

    # --------------------------------------------------
    # CIELCHab
    # --------------------------------------------------

    pdf.setFont("Helvetica-Bold", 14)

    pdf.drawString(
        50,
        y,
        "CIELCHab Coordinates"
    )

    pdf.setFont("Helvetica", 12)

    y -= 25

    pdf.drawString(
        70,
        y,
        f"L*: {L:.2f}"
    )

    y -= 20

    pdf.drawString(
        70,
        y,
        f"C*: {C:.2f}"
    )

    y -= 20

    pdf.drawString(
        70,
        y,
        f"h°: {h:.1f}"
    )

    y -= 40

    # --------------------------------------------------
    # XYZ
    # --------------------------------------------------

    pdf.setFont("Helvetica-Bold", 14)

    pdf.drawString(
        50,
        y,
        "XYZ Tristimulus Values"
    )

    pdf.setFont("Helvetica", 12)

    y -= 25

    pdf.drawString(
        70,
        y,
        f"X: {XYZ[0]:.2f}"
    )

    y -= 20

    pdf.drawString(
        70,
        y,
        f"Y: {XYZ[1]:.2f}"
    )

    y -= 20

    pdf.drawString(
        70,
        y,
        f"Z: {XYZ[2]:.2f}"
    )

    y -= 40

    # --------------------------------------------------
    # Chromaticity
    # --------------------------------------------------

    pdf.setFont("Helvetica-Bold", 14)

    pdf.drawString(
        50,
        y,
        "Chromaticity Coordinates"
    )

    pdf.setFont("Helvetica", 12)

    y -= 25

    pdf.drawString(
        70,
        y,
        f"x: {xy[0]:.4f}"
    )

    y -= 20

    pdf.drawString(
        70,
        y,
        f"y: {xy[1]:.4f}"
    )

    y -= 40

    # --------------------------------------------------
    # Appearance properties
    # --------------------------------------------------

    pdf.setFont("Helvetica-Bold", 14)

    pdf.drawString(
        50,
        y,
        "Appearance Properties"
    )

    pdf.setFont("Helvetica", 12)

    y -= 25

    pdf.drawString(
        70,
        y,
        f"Gloss: {float(gloss):.2f}"
    )

    y -= 20

    pdf.drawString(
        70,
        y,
        f"RGB: ({rgb[0]}, {rgb[1]}, {rgb[2]})"
    )

    y -= 50

    # --------------------------------------------------
    # Colour patch
    # --------------------------------------------------

    pdf.setFont("Helvetica-Bold", 14)

    pdf.drawString(
        50,
        y,
        "sRGB Preview"
    )

    patch_y = y - 80

    pdf.setFillColor(
        colors.Color(
            rgb[0] / 255,
            rgb[1] / 255,
            rgb[2] / 255
        )
    )

    pdf.rect(
        50,
        patch_y,
        80,
        80,
        fill=1,
        stroke=1
    )

    pdf.setFillColor(colors.black)

    # --------------------------------------------------
    # Footer
    # --------------------------------------------------

    pdf.setFont(
        "Helvetica-Oblique",
        9
    )

    pdf.drawString(
        50,
        40,
        "Generated by CM-26dG Colour Explorer"
    )

    # --------------------------------------------------
    # Save
    # --------------------------------------------------

    pdf.save()

    buffer.seek(0)

    return buffer